services:  
  db:
    image: postgres:15-alpine
    container_name: nexa_db
    restart: always
    environment:
      POSTGRES_USER: nexa_user
      POSTGRES_PASSWORD: nexa_password
      POSTGRES_DB: nexa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      target: build
    container_name: nexa_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: nexa_user
      DB_PASS: nexa_password
      DB_NAME: nexa_db
      JWT_SECRET: supersecret

    volumes:
      - ./backend:/app             # 👈 O Túnel: conecta seu Linux Mint ao Container
      - /app/node_modules          # 👈 Mantém as bibliotecas isoladas
    command: npx ts-node-dev --respawn --transpile-only src/index.ts # 👈 Faz atualizar ao salvar

  frontend:  
    build: ./frontend
    container_name: nexa_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: